// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVMsS3Z8MBzZPBnJUfT9LjAs3YAC12L6Q',
    appId: '1:233447789411:web:69dd31bee0b6be76527956',
    messagingSenderId: '233447789411',
    projectId: 'syndic-163b9',
    authDomain: 'syndic-163b9.firebaseapp.com',
    storageBucket: 'syndic-163b9.firebasestorage.app',
    measurementId: 'G-4VYXCTHY2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrg_pim94Q_BaSzKvmvVY0FGSWbzHXjfQ',
    appId: '1:233447789411:android:850b23d43890d358527956',
    messagingSenderId: '233447789411',
    projectId: 'syndic-163b9',
    storageBucket: 'syndic-163b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9N4VvgQkQJfR6vreTJ3axhVH5KnFN_Ps',
    appId: '1:233447789411:ios:f0a963fe45b58536527956',
    messagingSenderId: '233447789411',
    projectId: 'syndic-163b9',
    storageBucket: 'syndic-163b9.firebasestorage.app',
    iosBundleId: 'com.wahda.sy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVMsS3Z8MBzZPBnJUfT9LjAs3YAC12L6Q',
    appId: '1:233447789411:web:3336a427fa436027527956',
    messagingSenderId: '233447789411',
    projectId: 'syndic-163b9',
    authDomain: 'syndic-163b9.firebaseapp.com',
    storageBucket: 'syndic-163b9.firebasestorage.app',
    measurementId: 'G-HH1EME9HJJ',
  );
}
